### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mrkaban** [stefansundin/xn_resource_editor#5]
Hello, what license is the program distributed under? It is not specified in the source code, nor in the program, nor on the project page. There is no such information anywhere. Please write it down, because without this information, the use of this program can cause problems with law enforcement agencies in some countries.

**Comment by ongun-kanat** [comment]
https://web.archive.org/web/20120307192859fw_/http://www.wilsonc.demon.co.uk/delphi_2006.htm

It seems to be MPL

**Comment by stefansundin** [comment]
Good detective work @ongun-kanat. Since the last release of XN Resource Editor was in 2005, it can't be under MPL 2.0.

Quote from the website in case it ever disappears ([screenshot](https://user-images.githubusercontent.com/1991151/97660254-3a11e080-1a2e-11eb-89fd-e74154a1d8eb.png)):
> The source files are released under the MPL public license, so you can use them to develop even commercial applications.

Some of the source files reference MPL 1.1, but not all of them. But together with the quote from the website I think we can assume that all of the files are under MPL 1.1.

https://github.com/stefansundin/xn_resource_editor/blob/1fc8b20166760878b33e2d67a257770111878272/Source/PropertyBaseForm.pas#L6-L9

I'm going to add a LICENSE file with MPL 1.1 so it shows up in the repository info.

**Comment by mrkaban** [comment]
Thank you very much for the free open source program!

Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%83%D1%82%D0%B8%D0%BB%D0%B8%D1%82%D1%8B/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/xn-resource-editor.html).
